spring:
  jpa:
    show-sql: true
    hibernate:
#      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/seatbookingsystem
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver