spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: DATABASEURI
    username: YOURUSERNAME
    password: YOURPASSWORD
    driver-class-name: org.postgresql.Driver